name: GitHub Actions Demo
on: [push]
jobs:
  Build-And-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn
      - run: yarn test
  Static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn
      - run: yarn audit
  Deploy:
      needs: 
        - Build-And-Test
        - Static-analysis
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.12.12
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: think-it-workshop
            heroku_email: akremkhezami@think-it.io
    zap_scan:
      needs: Deploy
      runs-on: ubuntu-latest
      name: Scan the webapplication
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: ZAP Scan
          uses: zaproxy/action-full-scan@v0.3.0
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            docker_name: 'owasp/zap2docker-stable'
            target: 'https://think-it-workshop.herokuapp.com/'
            rules_file_name: 'rules.tsv'
            fail_action: true
            cmd_options: '-a -i'


